# Generated by Django 3.1.14 on 2022-04-13 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobapp', '0002_auto_20200422_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profession',
            field=models.IntegerField(choices=[(1, 'IT/ Telecomunication'), (2, 'Construction/ Engineering/ Architects'), (3, 'Health Care/ Pharma/ Biotech/ Medical/ R&D'), (4, 'Banking/ Insurance/ Financial Services'), (5, 'Teaching/ Education'), (6, 'General Management/ Administration')], default=1),
        ),
    ]
